plugins/spender: fix false positive init warning from gcc-12 -O3.
In practice, this is behind a branch where it can't occur: gcc-13 doesn't
mind, but gcc-12 does.

```
In function ‘handle_fee_and_ppm’,
    inlined from ‘continue_splice.part.0’ at plugins/spender/splice.c:1669:12:
plugins/spender/splice.c:1415:38: error: ‘funding_wallet_index’ may be used uninitialized [-Werror=maybe-uninitialized]
 1415 |                 && splice_cmd->states[funding_wallet_index]->state != SPLICE_CMD_PENDING) {
      |                                      ^
plugins/spender/splice.c: In function ‘continue_splice.part.0’:
plugins/spender/splice.c:1394:16: note: ‘funding_wallet_index’ was declared here
 1394 |         size_t funding_wallet_index;
      |                ^~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
(cherry picked from commit c32111abea09ebe7385e19afbd869c7a3bcda922)
[ uses the two-argument COMPILER_WANTS_INIT, as master has since b2d59056a5 ]
(cherry picked from commit 9f58f11acfd6ab94481db0042902e7fc286d4a96)